// Explicit prototypes because implementation is split across include files.
void activity();
void centerText(const String& s, int y, uint16_t color = C_MAIN);
String shorten(const String& s, int n);
bool containsArabic(const String& s);
int utf8ToCodepoints(const String& s, uint16_t* out, int maxOut);
bool getArForm(uint16_t base, ArForm& f);
bool joinsPrev(uint16_t cp);
bool joinsNext(uint16_t cp);
int shapeArabic(const uint16_t* in, int n, uint16_t* out);
bool isLTRChar(uint16_t cp);
int makeVisualRTL(const uint16_t* shaped, int n, uint16_t* visual);
bool getArabicGlyph(uint16_t cp, ArGlyphMeta& g);
int asciiAdvance(uint16_t cp);
int visualWidth(const uint16_t* v, int n);
void drawArabicGlyph(uint16_t cp, int x, int baseline, uint16_t color);
int arabicLineWidth(const String& s);
void drawArabicLine(const String& s, int rightX, int baseline, uint16_t color);
void drawArabicWrapped(const String& text, int rightX, int y, int width, int maxLines, uint16_t color);
void drawArabicWrappedCentered(const String& text, int centerX, int y, int width, int maxLines, uint16_t color);
bool getEnglishGlyph(uint8_t cp, EnGlyphMeta& g);
int englishTextWidth16(const String& s);
void drawEnglishGlyph16(uint8_t cp, int x, int baseline, uint16_t color);
void drawEnglishLine16(const String& s, int centerX, int baseline, uint16_t color);
void drawEnglishWrappedCentered(const String& text, int centerX, int y, int width, int maxLines, uint16_t color);
void wrapped(const String& text, int x, int y, int width, int maxLines, uint16_t color);
Mood parseMood(String s);
String moodName();
void applyTheme();
void saveSettings();
void loadSettings();
void getClock(int &hour, int &minute);
String clockText();
void drawTopBar();
int batteryPercent();
void drawBattery();
void eyeDot(int x, int y);
void solidBar(int x, int y, int w, int h = 5);
void solidOpenMouth(int cx, int topY, int w = 30, int h = 18);
void solidSmile(int cx, int cy, int w = 32, int h = 17);
void solidFrown(int cx, int cy, int w = 30, int h = 16);
void solidHappyEye(int cx, int cy);
void solidSadEye(int cx, int cy);
void drawHeart(int x, int y);
void redrawNeutralEyesOnly();
void drawNeutralFace();
void drawHappyFace();
void drawLoveFace();
void drawSurprisedFace();
void drawSadFace();
void drawAngryFace();
void drawDeadFace();
void drawSleepFace();
void drawRecordingFace();
void drawTypingFace();
void drawBirthdayCake();
void drawReactionFace(Mood r);
void drawFace();
void animateFace();
void drawChat();
void drawMenu();
void drawAppearanceMenu();
void drawBrightnessSet();
void drawTimeSet();
void drawColorSet();
void drawThemeSet();
void drawAbout();
void openMenu();
void drawNetworks();
void scanNetworks();
int rowLength();
void drawKeyboard();
bool connectWiFi(const String& ssid, const String& password, bool saveIt);
void trySavedWiFi();
void le16(uint8_t* p, uint16_t v);
void le32(uint8_t* p, uint32_t v);
String toBase64(const uint8_t* data, size_t len);
bool askGemini();
void playLokiResponseSound();
void stopBirthdaySong();
void startBirthdaySong();
void updateBirthdaySong();
void beginRecording();
void recordFrame();
void finishRecording();
void drawError();
void updateTopButton();
bool topWasHold();
bool topWasClicked();
bool topIsPressed();
void handleButtons();
void setup();
void loop();
uint8_t* makeWav(size_t& wavSize);
